base_url = "https://blackmesa.dhopcs.org/docs/"
title = "Black Mesa"
description = "Moderation for the server owner who loves configuration."
compile_sass = false
build_search_index = true
minify_html = true

[markdown]

[markdown.highlighting]
code = true
style = "inline"
theme = "github-dark"

[extra]
repo_url = "https://github.com/blackmesadev/black-mesa"
discord_url = "https://discord.gg/ZezqXEXBDJ"
